In [7]:
import pandas as pd
import numpy as np

In [8]:
with open("../results.csv", "r") as f:
    df = pd.read_csv(f, sep=" ", dtype=str, keep_default_na=False)
df

,hash,rng,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,N,Mtot,curtask,Ntasks,sum,sum2,chi2cdf
0,166a320f22d7c6b2,1,0,16,True,True,1,2,20,2,0,1,20,250,0.9746526813225317
1,10f5df379ce0ac39,1,0,16,True,True,1,2,40,2,0,1,40,850,0.886153701993342
2,1fbd7d92281713ca,1,0,16,True,True,1,4,40,4,0,1,40,438,0.7161138692401724
3,072ce13c71ca6878,1,0,16,True,True,2,2,40,4,0,1,40,450,0.8282028557032669
4,073c5a4db752edfe,1,0,16,True,True,1,4,80,4,0,1,80,1666,0.6523573552677251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,4e4e1be81f543b4e,1,0,None,True,True,8,2,256000000,256,0,1,256000000,256000262534152,0.6405172707578647
1891,04613ab928c6ac10,1,0,8,True,True,1,128,128000000,128,0,1,128000000,128000134743486,0.6977602297294504
1892,4fc75e1a6abc368c,1,0,8,True,True,7,2,128000000,128,0,1,128000000,128000124252262,0.44759267195831753
1893,0246f66103f77d85,1,0,16,True,True,1,128,128000000,128,0,1,128000000,128000124271046,0.4480654678634532
1894,0bd9b42657d9acff,1,0,16,True,True,7,2,128000000,128,0,1,128000000,128000135257434,0.7084698792058697

In [9]:
mask = (df.sum2.str.len() > 0)

In [10]:
df_filtered = df[mask]
df_filtered

,hash,rng,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,N,Mtot,curtask,Ntasks,sum,sum2,chi2cdf
0,166a320f22d7c6b2,1,0,16,True,True,1,2,20,2,0,1,20,250,0.9746526813225317
1,10f5df379ce0ac39,1,0,16,True,True,1,2,40,2,0,1,40,850,0.886153701993342
2,1fbd7d92281713ca,1,0,16,True,True,1,4,40,4,0,1,40,438,0.7161138692401724
3,072ce13c71ca6878,1,0,16,True,True,2,2,40,4,0,1,40,450,0.8282028557032669
4,073c5a4db752edfe,1,0,16,True,True,1,4,80,4,0,1,80,1666,0.6523573552677251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,4e4e1be81f543b4e,1,0,None,True,True,8,2,256000000,256,0,1,256000000,256000262534152,0.6405172707578647
1891,04613ab928c6ac10,1,0,8,True,True,1,128,128000000,128,0,1,128000000,128000134743486,0.6977602297294504
1892,4fc75e1a6abc368c,1,0,8,True,True,7,2,128000000,128,0,1,128000000,128000124252262,0.44759267195831753
1893,0246f66103f77d85,1,0,16,True,True,1,128,128000000,128,0,1,128000000,128000124271046,0.4480654678634532
1894,0bd9b42657d9acff,1,0,16,True,True,7,2,128000000,128,0,1,128000000,128000135257434,0.7084698792058697

In [11]:
df_filtered.to_csv("../results_corr.csv", sep=' ', index=False)