In [1]:
import pandas as pd
import numpy as np

In [2]:
with open("../results.csv", "r") as f:
    df = pd.read_csv(f, sep=" ", dtype=str, keep_default_na=False)
df

,,,hash,rng,offset,dim,m,N,Mtot,curtask,Ntasks,sum,sum2,chi2cdf
166a320f22d7c6b2,1,0,16,True,True,1,2,20,2,0,1,20,250,0.9746526813225317
10f5df379ce0ac39,1,0,16,True,True,1,2,40,2,0,1,40,850,0.886153701993342
1fbd7d92281713ca,1,0,16,True,True,1,4,40,4,0,1,40,438,0.7161138692401724
072ce13c71ca6878,1,0,16,True,True,2,2,40,4,0,1,40,450,0.8282028557032669
073c5a4db752edfe,1,0,16,True,True,1,4,80,4,0,1,80,1666,0.6523573552677251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130775b1dff99f1d,1,0,None,6,16,335544320,16777216,0,1,335544320,7046444690,0.5481032121430545,,
0de5f4201076646a,1,0,None,2,4096,838860800,16777216,0,1,838860800,42781778346,0.3363205352377561,,
750fdef40f333022,1,0,None,6,16,838860800,16777216,0,1,838860800,42781856394,0.4391856378679581,,
09994dead9f06f43,1,0,None,5,32,671088640,33554432,0,1,671088640,14092802166,0.35883034627844035,,
47f230058cd89252,1,0,None,8,8,838860800,16777216,0,1,838860800,42782024644,0.6656231538448301,,

In [3]:
mask = (df.sum2.str.len() > 0)

In [4]:
df_filtered = df[mask]
df_filtered

,,,hash,rng,offset,dim,m,N,Mtot,curtask,Ntasks,sum,sum2,chi2cdf
166a320f22d7c6b2,1,0,16,True,True,1,2,20,2,0,1,20,250,0.9746526813225317
10f5df379ce0ac39,1,0,16,True,True,1,2,40,2,0,1,40,850,0.886153701993342
1fbd7d92281713ca,1,0,16,True,True,1,4,40,4,0,1,40,438,0.7161138692401724
072ce13c71ca6878,1,0,16,True,True,2,2,40,4,0,1,40,450,0.8282028557032669
073c5a4db752edfe,1,0,16,True,True,1,4,80,4,0,1,80,1666,0.6523573552677251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27329242d53b509b,1,0,8,True,True,1,16777216,838860800,16777216,0,1,838860800,2748779907767238,1.0
34760d8ddbc483d0,1,0,8,True,True,8,4,655360000,65536,0,1,655360000,6554253900026,0.3449615037894817
1bb7a613cc5016b8,1,0,8,True,True,5,32,671088640,33554432,0,1,671088640,14092855278,0.4850804340111768
124cc7eb10d12fdc,1,0,8,True,True,8,8,838860800,16777216,0,1,838860800,42781902290,0.5021671225662115
1577d8fb7b7c2967,1,0,8,True,True,2,4096,838860800,16777216,0,1,838860800,10738256001696,1.0

In [5]:
df_filtered.to_csv("../results_corr.csv", sep=' ') #, index=False)