In [34]:
import pandas as pd
import numpy as np

In [39]:
with open("../results.csv", "r") as f:
    df = pd.read_csv(f, sep="\s+", dtype='str', keep_default_na=False)
df

,hash,date,time,elapsed,rng,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
0,2328d7d51b69aa46,2025.10.08,08:08:03,1.11e-03,1,0,8,0,0,1,2,1,20,2,0,1,20,202,3.452791539814230e-01,1
1,0bf5c7b73b605c41,2025.10.08,08:08:03,2.54e-04,1,0,8,0,0,1,2,2,20,2,0,1,20,202,3.452791539814230e-01,1
2,06c5f05cc73e5e3a,2025.10.08,08:08:03,3.48e-04,1,0,8,0,0,1,2,3,20,2,0,1,20,202,3.452791539814230e-01,1
3,1de1446a8bca2727,2025.10.08,08:08:03,2.80e-04,1,0,8,0,0,1,2,4,20,2,0,1,20,202,3.452791539814230e-01,1
4,4b5b77d57216a95a,2025.10.08,08:08:03,3.49e-04,1,0,8,0,0,1,2,5,20,2,0,1,20,232,9.263617298796973e-01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45642,5b0a9d95e9f6b568,2025.10.24,23:02:16,5.16e+03,1,0,16,1,1,5,10,8,10000000000,100000,0,1,10000000000,1000010012285638,3.684624952247000e-01,1
45643,6c0483155e0f61ef,2025.10.24,23:03:18,1.36e+04,1,0,16,1,0,7,10,9,10000000000,10000000,0,1,10000000000,10010002991746,7.225993333332424e-01,1
45644,13d6cb948de589c3,2025.10.25,03:12:04,1.99e-03,1,0,16,0,0,1,4096,0,40960,4096,0,1,40960,1677721600,1.000000000000000e+00,1
45645,13d6cb948de589c3,2025.10.25,03:12:53,9.38e-03,1,0,16,0,0,1,4096,0,40960,4096,0,1,40960,1677721600,1.000000000000000e+00,1
45646,13d6cb948de589c3,2025.10.25,03:14:19,7.08e+01,1,0,16,0,0,1,4096,0,40960,4096,0,1,40960,1677721600,1.000000000000000e+00,1

In [40]:
mask = (df.stride != '0')

In [41]:
df_filtered = df[mask]
df_filtered

,hash,date,time,elapsed,rng,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,stride,N,Mtotal,curtask,Ntasks,sum,sum2,chi2cdf,parameters_ok
0,2328d7d51b69aa46,2025.10.08,08:08:03,1.11e-03,1,0,8,0,0,1,2,1,20,2,0,1,20,202,3.452791539814230e-01,1
1,0bf5c7b73b605c41,2025.10.08,08:08:03,2.54e-04,1,0,8,0,0,1,2,2,20,2,0,1,20,202,3.452791539814230e-01,1
2,06c5f05cc73e5e3a,2025.10.08,08:08:03,3.48e-04,1,0,8,0,0,1,2,3,20,2,0,1,20,202,3.452791539814230e-01,1
3,1de1446a8bca2727,2025.10.08,08:08:03,2.80e-04,1,0,8,0,0,1,2,4,20,2,0,1,20,202,3.452791539814230e-01,1
4,4b5b77d57216a95a,2025.10.08,08:08:03,3.49e-04,1,0,8,0,0,1,2,5,20,2,0,1,20,232,9.263617298796973e-01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45638,70ab2dbe1beab14c,2025.10.24,22:53:11,2.71e+03,1,0,16,1,1,7,10,4,10000000000,10000000,0,1,10000000000,10009998600608,3.427989106621843e-01,1
45639,1c44e809f112078a,2025.10.24,22:53:58,1.58e+03,1,0,16,1,1,8,10,2,10000000000,100000000,0,1,10000000000,1009999040256,2.371519641002998e-01,1
45641,7378375ee7bbf4a6,2025.10.24,22:59:47,6.10e+03,1,0,16,1,1,4,100,9,10000000000,100000000,0,1,10000000000,1010002552634,6.093118367817565e-01,1
45642,5b0a9d95e9f6b568,2025.10.24,23:02:16,5.16e+03,1,0,16,1,1,5,10,8,10000000000,100000,0,1,10000000000,1000010012285638,3.684624952247000e-01,1
45643,6c0483155e0f61ef,2025.10.24,23:03:18,1.36e+04,1,0,16,1,0,7,10,9,10000000000,10000000,0,1,10000000000,10010002991746,7.225993333332424e-01,1

In [42]:
df_filtered.to_csv("../results_corr.csv", sep=' ', index=False)