In [96]:
import pandas as pd
import numpy as np

In [97]:
dtype_spec = {"sum": np.int64, "sum2": np.int64, "chi2cdf": np.float64}
with open("../results_corr.csv", "r") as f:
    df = pd.read_csv(f, sep=" ", dtype=dtype_spec, keep_default_na=False, )
df

,hash,rng,offset,bitsPerSample,srcLittleEndian,dstLittleEndian,dim,m,N,Mtot,curtask,Ntasks,sum,sum2,chi2cdf
0,166a320f22d7c6b2,1,0,16,True,True,1,2,20,2,0,1,20,250,0.974653
1,10f5df379ce0ac39,1,0,16,True,True,1,2,40,2,0,1,40,850,0.886154
2,1fbd7d92281713ca,1,0,16,True,True,1,4,40,4,0,1,40,438,0.716114
3,072ce13c71ca6878,1,0,16,True,True,2,2,40,4,0,1,40,450,0.828203
4,073c5a4db752edfe,1,0,16,True,True,1,4,80,4,0,1,80,1666,0.652357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,4e4e1be81f543b4e,1,0,None,True,True,8,2,256000000,256,0,1,256000000,256000262534152,0.640517
1891,04613ab928c6ac10,1,0,8,True,True,1,128,128000000,128,0,1,128000000,128000134743486,0.697760
1892,4fc75e1a6abc368c,1,0,8,True,True,7,2,128000000,128,0,1,128000000,128000124252262,0.447593
1893,0246f66103f77d85,1,0,16,True,True,1,128,128000000,128,0,1,128000000,128000124271046,0.448065
1894,0bd9b42657d9acff,1,0,16,True,True,7,2,128000000,128,0,1,128000000,128000135257434,0.708470

In [101]:
mask = (df.chi2cdf > 0.999)
df2 = df[mask].copy()
#df2
df2.groupby(["dim", "bitsPerSample"]).count()

                   hash  rng  offset  srcLittleEndian  dstLittleEndian    m  \
dim bitsPerSample
1   16               59   59      59               59               59   59
    8               150  150     150              150              150  150
2   16                4    4       4                4                4    4
    8                57   57      57               57               57   57
3   8                28   28      28               28               28   28
4   8                18   18      18               18               18   18
5   8                11   11      11               11               11   11
6   8                 5    5       5                5                5    5
7   8                 4    4       4                4                4    4

                     N  Mtot  curtask  Ntasks  sum  sum2  chi2cdf
dim bitsPerSample
1   16              59    59       59      59   59    59       59
    8              150   150      150     150  150   150      150
2   16               4     4        4       4    4     4        4
    8               57    57       57      57   57    57       57
3   8               28    28       28      28   28    28       28
4   8               18    18       18      18   18    18       18
5   8               11    11       11      11   11    11       11
6   8                5     5        5       5    5     5        5
7   8                4     4        4       4    4     4        4

In [102]:
df.groupby(["dim", "bitsPerSample"]).count()

                   hash  rng  offset  srcLittleEndian  dstLittleEndian    m  \
dim bitsPerSample
1   16              232  232     232              232              232  232
    8               232  232     232              232              232  232
    None            234  234     234              234              234  234
2   16              124  124     124              124              124  124
    8               124  124     124              124              124  124
    None            125  125     125              125              125  125
3   16               82   82      82               82               82   82
    8                82   82      82               82               82   82
    None             82   82      82               82               82   82
4   16               55   55      55               55               55   55
    8                55   55      55               55               55   55
    None             56   56      56               56               56   56
5   16               38   38      38               38               38   38
    8                38   38      38               38               38   38
    None             38   38      38               38               38   38
6   16               28   28      28               28               28   28
    8                28   28      28               28               28   28
    None             28   28      28               28               28   28
7   16               21   21      21               21               21   21
    8                21   21      21               21               21   21
    None             21   21      21               21               21   21
8   16               16   16      16               16               16   16
    8                16   16      16               16               16   16
    None             17   17      17               17               17   17
9   16               12   12      12               12               12   12
    8                12   12      12               12               12   12
    None             12   12      12               12               12   12
10  16               11   11      11               11               11   11
    8                11   11      11               11               11   11
    None             11   11      11               11               11   11
11  16               11   11      11               11               11   11
    8                11   11      11               11               11   11
    None             11   11      11               11               11   11

                     N  Mtot  curtask  Ntasks  sum  sum2  chi2cdf
dim bitsPerSample
1   16             232   232      232     232  232   232      232
    8              232   232      232     232  232   232      232
    None           234   234      234     234  234   234      234
2   16             124   124      124     124  124   124      124
    8              124   124      124     124  124   124      124
    None           125   125      125     125  125   125      125
3   16              82    82       82      82   82    82       82
    8               82    82       82      82   82    82       82
    None            82    82       82      82   82    82       82
4   16              55    55       55      55   55    55       55
    8               55    55       55      55   55    55       55
    None            56    56       56      56   56    56       56
5   16              38    38       38      38   38    38       38
    8               38    38       38      38   38    38       38
    None            38    38       38      38   38    38       38
6   16              28    28       28      28   28    28       28
    8               28    28       28      28   28    28       28
    None            28    28       28      28   28    28       28
7   16              21    21       21      21   21    21       21
    8               21    21       21      21   21    21       21
    None            21    21       21      21   21    21       21
8   16              16    16       16      16   16    16       16
    8               16    16       16      16   16    16       16
    None            17    17       17      17   17    17       17
9   16              12    12       12      12   12    12       12
    8               12    12       12      12   12    12       12
    None            12    12       12      12   12    12       12
10  16              11    11       11      11   11    11       11
    8               11    11       11      11   11    11       11
    None            11    11       11      11   11    11       11
11  16              11    11       11      11   11    11       11
    8               11    11       11      11   11    11       11
    None            11    11       11      11   11    11       11

In [99]:
pivot = pd.pivot_table(df2, columns=["N"], index="dim", values="N")
pivot

ValueError: Grouper for 'N' not 1-dimensional